version: "2"

run:
  tests: true

linters:
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - errcheck
      - path: "cmd/"
        linters:
          - errcheck
      - path: "_test.go"
        linters:
          - staticcheck
        text: "implement StmtQueryContext"
      - path: "_test.go"
        linters:
          - staticcheck
        text: "implement StmtExecContext"
      - linters:
          - staticcheck
        text: "QF1001"