parsers:
  go:
    partials_as_hits: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%

flags:
  unittests:
    paths:
      - "."
      - "internal/"
      - "sflog/"
    carryforward: true