[[constraint]]
  branch = "master"
  name = "github.com/snowflakedb/glog"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
