[[constraint]]
  branch = "master"
  name = "github.com/pkg/browser"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/golang/glog"
  source = "https://github.com/snowflakedb/glog.git"
  branch = "master"