[default]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_default_user'
password = 'test_default_pass'
warehouse = 'testw_default'
database = 'test_default_db'
schema = 'test_default_go'
protocol = 'https'
port = '300'

[aws-oauth]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_oauth_user'
password = 'test_oauth_pass'
warehouse = 'testw_oauth'
database = 'test_oauth_db'
schema = 'test_oauth_go'
protocol = 'https'
port = '443'
authenticator = 'oauth'
testNot = 'problematicParameter'
token = 'token_value'
disableOCSPChecks = true

[aws-oauth-file]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_user'
password = 'test_pass'
warehouse = 'testw'
database = 'test_db'
schema = 'test_go'
protocol = 'https'
port = '443'
authenticator = 'oauth'
testNot = 'problematicParameter'
token_file_path = '/Users/test/.snowflake/token'

[read-token]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_default_user'
password = 'test_default_pass'
warehouse = 'testw_default'
database = 'test_default_db'
schema = 'test_default_go'
protocol = 'https'
authenticator = 'oauth'
token_file_path = './test_data/snowflake/session/token'
insecureMode = true