[default]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_user'
password = 'test_pass'
warehouse = 'testw'
database = 'test_db'
schema = 'test_go'
protocol = 'https'
port = '443'

[aws-oauth]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_user'
password = 'test_pass'
warehouse = 'testw'
database = 'test_db'
schema = 'test_go'
protocol = 'https'
port = '443'
authenticator = 'oauth'
testNot = 'problematicParameter'
token = 'token_value'

[aws-oauth-file]
account = 'snowdriverswarsaw.us-west-2.aws'
user = 'test_user'
password = 'test_pass'
warehouse = 'testw'
database = 'test_db'
schema = 'test_go'
protocol = 'https'
port = '443'
authenticator = 'oauth'
testNot = 'problematicParameter'
token_file_path = '/Users/test/.snowflake/token'

[read-token]
authenticator = 'oauth'
token_file_path = './token_file/token'