name: Semgrep
on:
    pull_request:
        branches:
            - master
jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep
    steps:
    - uses: actions/checkout@v1
    - name: Semgrep
      id: semgrep
      uses: returntocorp/semgrep-action@v1
