name: Test Branch Name
on:
    pull_request:
        branches:
            - master
jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Test Branch
    steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.7'
        - name: PR title
          run: |
                echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
                echo ${title}
                python -c "import os; print(os.environ.get('title'))"
                t=`python -c 'import re; import os; snow_list = re.findall(r"(?:SNOW|snow|Snow)-\d+", os.environ["title"]); print(len(snow_list))'`
                echo ${t}
                echo ${{ github.event.pull_request.title }}
